// ag-grid-react-v35/src/App.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/styles/ag-grid.css';
import { createViewportDatasource, getMockServerConfig, updateMockServerConfig } from './mockServer';

const FRAMEWORK = 'react';
const AVAILABLE_VERSIONS = ['32', '33', '35'];
const DEFAULT_CONFIG = {
  latencyMs: 70,
  tickRateMs: 100,
  totalRows: 100000
};

const DEFAULT_GRID_CONFIG = {
  rowBuffer: 0,
  viewportRowModelBufferSize: 20
};

const SYMBOLS = ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'META', 'NVDA', 'TSLA', 'JPM', 'V', 'WMT', 'JNJ', 'PG', 'MA', 'UNH', 'HD'];
const SIDE = ['BUY', 'SELL'];
const STATUS = ['PENDING', 'FILLED', 'PARTIAL', 'CANCELLED'];
const ORDER_TYPE = ['MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT'];
const VENUE = ['NYSE', 'NASDAQ', 'BATS', 'ARCA', 'CBOE', 'PHLX'];
const CURRENCY = ['USD', 'EUR', 'GBP', 'JPY'];
const REGION = ['NA', 'EU', 'APAC', 'LATAM'];
const SECTOR = ['Technology', 'Healthcare', 'Finance', 'Energy', 'Consumer', 'Industrial', 'Materials', 'Utilities'];
const PRIORITY = ['HIGH', 'MEDIUM', 'LOW', 'URGENT'];
const ALGO = ['VWAP', 'TWAP', 'POV', 'IS', 'AUCO', 'PRIORITY'];

function getCurrentVersion() {
  if (typeof window === 'undefined') {
    return '35';
  }

  return window.location.pathname.match(/-v(\d+)(?:\/|$)/)?.[1] ?? '35';
}

function getVersionHref(nextVersion) {
  return new URL(`../ag-grid-${FRAMEWORK}-v${nextVersion}/`, window.location.href).toString();
}

function attachViewportDatasource(api, datasource) {
  if (typeof api.setGridOption === 'function') {
    api.setGridOption('viewportDatasource', datasource);
    return;
  }

  if (typeof api.setViewportDatasource === 'function') {
    api.setViewportDatasource(datasource);
  }
}

function randomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateTrade(id) {
  const basePrice = Math.random() * 1000 + 50;
  const quantity = Math.floor(Math.random() * 1000) + 1;
  const limitPrice = parseFloat((basePrice * (0.9 + Math.random() * 0.2)).toFixed(2));
  return {
    id: `TRD-${String(id).padStart(6, '0')}`,
    orderId: `ORD-${String(Math.floor(Math.random() * 1000000)).padStart(8, '0')}`,
    symbol: randomElement(SYMBOLS),
    side: randomElement(SIDE),
    orderType: randomElement(ORDER_TYPE),
    quantity,
    filledQuantity: Math.floor(Math.random() * quantity),
    limitPrice,
    marketPrice: parseFloat(basePrice.toFixed(2)),
    avgPrice: parseFloat(basePrice.toFixed(2)),
    status: randomElement(STATUS),
    timestamp: Date.now() - Math.floor(Math.random() * 86400000),
    trader: `TRADER-${Math.floor(Math.random() * 100)}`,
    account: `ACC-${Math.floor(Math.random() * 1000)}`,
    venue: randomElement(VENUE),
    commission: parseFloat((Math.random() * 10).toFixed(2)),
    currency: randomElement(CURRENCY),
    region: randomElement(REGION),
    sector: randomElement(SECTOR),
    settlementDate: new Date(Date.now() + Math.floor(Math.random() * 3) * 86400000).toISOString().split('T')[0],
    notional: parseFloat((basePrice * quantity).toFixed(2)),
    priority: randomElement(PRIORITY),
    algo: randomElement(ALGO),
    executionVenue: randomElement(VENUE),
    counterparty: `CP-${Math.floor(Math.random() * 100)}`,
    bloombergId: `BBG${Math.floor(Math.random() * 10000000)}`,
    ricCode: `${randomElement(SYMBOLS)}.${randomElement(['OQ', 'US', 'OB', 'UP'])}`,
    cusip: Math.random().toString(36).substring(2, 11).toUpperCase(),
    isin: `${randomElement(['US', 'GB', 'DE', 'FR'])}${Math.random().toString(36).substring(2, 12).toUpperCase()}`,
    sedol: Math.random().toString(36).substring(2, 9).toUpperCase(),
    __index: id - 1
  };
}

const columnDefs = [
  { field: 'id', headerName: 'Trade ID', width: 110, pinned: 'left' },
  { field: 'orderId', headerName: 'Order ID', width: 120 },
  { field: 'symbol', headerName: 'Symbol', width: 70 },
  { field: 'side', headerName: 'Side', width: 60,
    cellStyle: (params) => params.value === 'BUY' ? { color: '#00ff88' } : { color: '#ff4757' }
  },
  { field: 'orderType', headerName: 'Type', width: 80 },
  { field: 'quantity', headerName: 'Qty', width: 60, type: 'numericColumn' },
  { field: 'filledQuantity', headerName: 'Filled', width: 70, type: 'numericColumn' },
  { field: 'limitPrice', headerName: 'Limit', width: 80, type: 'numericColumn',
    valueFormatter: (params) => params.value ? `$${params.value.toFixed(2)}` : '',
    cellStyle: { textAlign: 'right' }
  },
  { field: 'marketPrice', headerName: 'Market', width: 80, type: 'numericColumn',
    valueFormatter: (params) => params.value ? `$${params.value.toFixed(2)}` : '',
    cellStyle: { textAlign: 'right' }
  },
  { field: 'avgPrice', headerName: 'Avg', width: 80, type: 'numericColumn',
    valueFormatter: (params) => params.value ? `$${params.value.toFixed(2)}` : '',
    cellStyle: { textAlign: 'right' }
  },
  { field: 'notional', headerName: 'Notional', width: 110, type: 'numericColumn',
    valueFormatter: (params) => params.value ? `$${params.value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '',
    cellStyle: { textAlign: 'right' }
  },
  { field: 'commission', headerName: 'Comm', width: 70, type: 'numericColumn',
    valueFormatter: (params) => params.value ? `$${params.value.toFixed(2)}` : '',
    cellStyle: { textAlign: 'right' }
  },
  { field: 'status', headerName: 'Status', width: 80,
    cellStyle: (params) => {
      const colors = { PENDING: '#ffa502', FILLED: '#00ff88', PARTIAL: '#00d4ff', CANCELLED: '#ff4757' };
      return { color: colors[params.value] || '#eee' };
    }
  },
  { field: 'trader', headerName: 'Trader', width: 75 },
  { field: 'account', headerName: 'Account', width: 75 },
  { field: 'venue', headerName: 'Venue', width: 70 },
  { field: 'currency', headerName: 'Curr', width: 60 },
  { field: 'region', headerName: 'Region', width: 60 },
  { field: 'sector', headerName: 'Sector', width: 90 },
  { field: 'settlementDate', headerName: 'Settle', width: 90 },
  { field: 'timestamp', headerName: 'Timestamp', width: 160,
    valueFormatter: (params) => params.value ? new Date(params.value).toISOString() : ''
  },
  { field: 'priority', headerName: 'Priority', width: 70 },
  { field: 'algo', headerName: 'Algo', width: 80 },
  { field: 'executionVenue', headerName: 'Exec Venue', width: 90 },
  { field: 'counterparty', headerName: 'Counterparty', width: 100 },
  { field: 'bloombergId', headerName: 'BBG ID', width: 90 },
  { field: 'ricCode', headerName: 'RIC', width: 80 },
  { field: 'cusip', headerName: 'CUSIP', width: 90 },
  { field: 'isin', headerName: 'ISIN', width: 100 },
  { field: 'sedol', headerName: 'SEDOL', width: 80 }
];

function ConfigInput({ label, value, min, step = 1, onChange }) {
  return (
    <label className="devtools-field">
      <span>{label}</span>
      <input type="number" min={min} step={step} value={value} onChange={onChange} />
    </label>
  );
}

function MockServerDevtools({ currentVersion, serverConfig, gridConfig, onApply }) {
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState({ ...serverConfig, ...gridConfig });
  const [dirty, setDirty] = useState(false);

  useEffect(() => {
    if (!open || !dirty) {
      setDraft({ ...serverConfig, ...gridConfig });
      setDirty(false);
    }
  }, [serverConfig, gridConfig, open, dirty]);

  const updateDraft = (field) => (event) => {
    setDirty(true);
    setDraft((prev) => ({
      ...prev,
      [field]: Number(event.target.value)
    }));
  };

  return (
    <div className={`devtools-shell ${open ? 'open' : ''}`}>
      <button className="devtools-toggle" type="button" onClick={() => setOpen((prev) => !prev)}>
        <span className="devtools-dot" />
        <span className="devtools-icon">Tools</span>
      </button>
      {open ? (
        <div className="devtools-panel">
          <div className="devtools-title">Mock Server</div>
          <div className="devtools-subtitle">Viewport controls</div>
          <label className="devtools-field">
            <span>AG Grid version</span>
            <select value={currentVersion} onChange={(event) => { window.location.href = getVersionHref(event.target.value); }}>
              {AVAILABLE_VERSIONS.map((version) => (
                <option key={version} value={version}>
                  v{version}
                </option>
              ))}
            </select>
          </label>
          <ConfigInput label="Latency ms" value={draft.latencyMs} min={0} onChange={updateDraft('latencyMs')} />
          <ConfigInput label="Tick rate ms" value={draft.tickRateMs} min={16} onChange={updateDraft('tickRateMs')} />
          <ConfigInput label="Total rows" value={draft.totalRows} min={50} onChange={updateDraft('totalRows')} />
          <ConfigInput label="Row buffer" value={draft.rowBuffer} min={0} onChange={updateDraft('rowBuffer')} />
          <ConfigInput label="Viewport buffer" value={draft.viewportRowModelBufferSize} min={0} onChange={updateDraft('viewportRowModelBufferSize')} />
          <div className="devtools-actions">
            <button type="button" className="devtools-ghost" onClick={() => { setDraft({ ...serverConfig, ...gridConfig }); setDirty(false); }}>Reset</button>
            <button type="button" className="devtools-primary" onClick={() => { setDirty(false); onApply(draft); }}>Apply</button>
          </div>
        </div>
      ) : null}
    </div>
  );
}

function App() {
  const currentVersion = getCurrentVersion();
  const [stats, setStats] = useState({ totalPnl: 0, tradeCount: 0, volume: 0 });
  const [serverConfig, setServerConfig] = useState(DEFAULT_CONFIG);
  const [gridConfig, setGridConfig] = useState(DEFAULT_GRID_CONFIG);
  const gridApiRef = useRef(null);
  const viewportDatasourceRef = useRef(null);

  useEffect(() => {
    void getMockServerConfig().then(setServerConfig).catch(() => {});

    return () => {
      viewportDatasourceRef.current?.destroy?.();
      viewportDatasourceRef.current = null;
    };
  }, []);

  const flashChangedCells = (rows) => {
    const api = gridApiRef.current;
    if (!api || rows.length === 0) {
      return;
    }

    requestAnimationFrame(() => {
      rows.forEach((row) => {
        const rowNode = api.getRowNode(String(row.__index));
        if (!rowNode) {
          return;
        }

        const columns = (row.__changedFields ?? [])
          .map((field) => api.getColumn(field))
          .filter(Boolean);

        if (columns.length === 0) {
          return;
        }

        api.flashCells({
          rowNodes: [rowNode],
          columns
        });
      });
    });
  };

  const onGridReady = ({ api }) => {
    gridApiRef.current = api;
    const datasource = createViewportDatasource({
      onStats: setStats,
      onRowCount: (rowCount) => setServerConfig((prev) => ({ ...prev, totalRows: rowCount })),
      onConfig: setServerConfig,
      onRowsUpdated: flashChangedCells
    });

    viewportDatasourceRef.current = datasource;
    attachViewportDatasource(api, datasource);
  };

  const applyConfig = async (nextConfig) => {
    const config = await updateMockServerConfig({
      latencyMs: nextConfig.latencyMs,
      tickRateMs: nextConfig.tickRateMs,
      totalRows: nextConfig.totalRows
    });
    setServerConfig(config);
    setGridConfig({
      rowBuffer: nextConfig.rowBuffer,
      viewportRowModelBufferSize: nextConfig.viewportRowModelBufferSize
    });
    viewportDatasourceRef.current?.refresh?.();
  };

  const defaultColDef = useMemo(() => ({
    sortable: true,
    resizable: true,
    suppressMovable: true
  }), []);

  return (
    <>
      <div className="container">
        <div className="header">
          <h1>AG Grid React v{currentVersion} - Viewport Row Model <span className="header-sub">Mocked server latency: {serverConfig.latencyMs}ms | Data tick rate: {serverConfig.tickRateMs}ms | Total rows: {serverConfig.totalRows.toLocaleString()}</span></h1>
          <div className="stats">
            <div className="stat">
              <span className="stat-label">Total P&L</span>
              <span className={`stat-value ${stats.totalPnl >= 0 ? 'positive' : 'negative'}`}>
                ${stats.totalPnl.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </span>
            </div>
            <div className="stat">
              <span className="stat-label">Trade Count</span>
              <span className="stat-value">{stats.tradeCount.toLocaleString()}</span>
            </div>
            <div className="stat">
              <span className="stat-label">Volume</span>
              <span className="stat-value">${(stats.volume / 1000000).toFixed(2)}M</span>
            </div>
          </div>
        </div>

        <div className="grid-container">
          <AgGridReact
            className="ag-theme-custom"
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            rowModelType="viewport"
            viewportRowModelPageSize={50}
            viewportRowModelBufferSize={gridConfig.viewportRowModelBufferSize}
            enableRangeSelection={true}
            animateRows={false}
            getRowId={(params) => String(params.data.__index)}
            onGridReady={onGridReady}
            rowBuffer={gridConfig.rowBuffer}
            suppressCellFocus={true}
          />
        </div>
      </div>
      <MockServerDevtools currentVersion={currentVersion} serverConfig={serverConfig} gridConfig={gridConfig} onApply={applyConfig} />
    </>
  );
}

export default App;

// ag-grid-angular-v32/src/app/app.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AgGridAngular } from 'ag-grid-angular';
import {
  CellClassParams,
  Column,
  ColDef,
  GetRowIdParams,
  GridApi,
  GridReadyEvent,
  IViewportDatasource
} from 'ag-grid-community';
import { createViewportDatasource, getMockServerConfig, MockServerConfig, MockServerStats, updateMockServerConfig, UpdatedViewportRow } from './mock-server';

const DEFAULT_CONFIG: MockServerConfig = {
  latencyMs: 70,
  tickRateMs: 100,
  totalRows: 100000
};

const DEFAULT_GRID_CONFIG = {
  rowBuffer: 0,
  viewportRowModelBufferSize: 20
};
const AVAILABLE_VERSIONS = ['32', '33', '35'];

const STATUS = ['PENDING', 'FILLED', 'PARTIAL', 'CANCELLED'];

interface Trade {
  id: string;
  orderId: string;
  symbol: string;
  side: string;
  orderType: string;
  quantity: number;
  filledQuantity: number;
  limitPrice: number;
  marketPrice: number;
  avgPrice: number;
  status: string;
  timestamp: number;
  trader: string;
  account: string;
  venue: string;
  commission: number;
  currency: string;
  region: string;
  sector: string;
  settlementDate: string;
  notional: number;
  priority: string;
  algo: string;
  executionVenue: string;
  counterparty: string;
  bloombergId: string;
  ricCode: string;
  cusip: string;
  isin: string;
  sedol: string;
  __index: number;
}

interface ColumnItem {
  field: string;
  headerName: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule, AgGridAngular],
  template: `
    <div class="container">
      <div class="header">
        <h1>AG Grid Angular v{{ currentVersion }} - Viewport Row Model <span class="header-sub">Mocked server latency: {{ serverConfig.latencyMs }}ms | Data tick rate: {{ serverConfig.tickRateMs }}ms | Total rows: {{ serverConfig.totalRows | number }}</span></h1>
        <div class="stats">
          <div class="stat">
            <span class="stat-label">Total P&L</span>
            <span [class.stat-value]="true" [class.positive]="totalPnl >= 0" [class.negative]="totalPnl < 0">
              {{ totalPnl | currency:'USD':'symbol':'1.2-2' }}
            </span>
          </div>
          <div class="stat">
            <span class="stat-label">Trade Count</span>
            <span class="stat-value">{{ tradeCount | number }}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Volume</span>
            <span class="stat-value">{{ (volume / 1000000) | number:'1.2-2' }}M</span>
          </div>
        </div>
      </div>

      <div class="grid-container">
        <ag-grid-angular
          class="ag-theme-custom"
          style="width: 100%; height: 100%;"
          [columnDefs]="columnDefs"
          [defaultColDef]="defaultColDef"
          [rowModelType]="'viewport'"
          [viewportDatasource]="viewportDatasource"
          [viewportRowModelPageSize]="50"
          [viewportRowModelBufferSize]="gridConfig.viewportRowModelBufferSize"
          [enableRangeSelection]="true"
          [animateRows]="false"
          [getRowId]="getRowId"
          [rowBuffer]="gridConfig.rowBuffer"
          [suppressCellFocus]="true"
          (gridReady)="onGridReady($event)"
        ></ag-grid-angular>
      </div>
    </div>

    <div class="devtools-shell" [class.open]="devtoolsOpen">
      <button class="devtools-toggle" type="button" (click)="toggleDevtools()">
        <span class="devtools-dot"></span>
        <span class="devtools-icon">Tools</span>
      </button>
      <div class="devtools-panel" *ngIf="devtoolsOpen">
        <div class="devtools-title">Mock Server</div>
        <div class="devtools-subtitle">Viewport controls</div>
        <label class="devtools-field">
          <span>AG Grid version</span>
          <select [ngModel]="currentVersion" (ngModelChange)="switchVersion($event)">
            <option *ngFor="let version of availableVersions" [ngValue]="version">v{{ version }}</option>
          </select>
        </label>
        <label class="devtools-field">
          <span>Latency ms</span>
          <input type="number" min="0" [(ngModel)]="draftConfig.latencyMs" (ngModelChange)="draftDirty = true" />
        </label>
        <label class="devtools-field">
          <span>Tick rate ms</span>
          <input type="number" min="16" [(ngModel)]="draftConfig.tickRateMs" (ngModelChange)="draftDirty = true" />
        </label>
        <label class="devtools-field">
          <span>Total rows</span>
          <input type="number" min="50" [(ngModel)]="draftConfig.totalRows" (ngModelChange)="draftDirty = true" />
        </label>
        <label class="devtools-field">
          <span>Row buffer</span>
          <input type="number" min="0" [(ngModel)]="draftGridConfig.rowBuffer" (ngModelChange)="draftDirty = true" />
        </label>
        <label class="devtools-field">
          <span>Viewport buffer</span>
          <input type="number" min="0" [(ngModel)]="draftGridConfig.viewportRowModelBufferSize" (ngModelChange)="draftDirty = true" />
        </label>
        <div class="devtools-actions">
          <button type="button" class="devtools-ghost" (click)="resetDraftConfig()">Reset</button>
          <button type="button" class="devtools-primary" (click)="applyConfig()">Apply</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host {
      height: 100vh;
      display: block;
    }

    .container {
      height: 100%;
      display: flex;
      flex-direction: column;
    }

    .header {
      padding: 16px 20px;
      background: #1a1a2e;
      color: white;
    }

    .header h1 {
      margin: 0 0 12px 0;
      font-size: 20px;
      font-weight: 600;
    }

    .header-sub {
      font-size: 12px;
      opacity: 0.7;
      font-weight: normal;
    }

    .stats {
      display: flex;
      gap: 24px;
    }

    .stat {
      display: flex;
      flex-direction: column;
    }

    .stat-label {
      font-size: 11px;
      text-transform: uppercase;
      opacity: 0.7;
      margin-bottom: 2px;
    }

    .stat-value {
      font-size: 18px;
      font-weight: 600;
    }

    .positive {
      color: #00ff88;
    }

    .negative {
      color: #ff4757;
    }

    .grid-container {
      flex: 1;
      overflow: hidden;
    }

    .devtools-shell {
      position: fixed;
      right: 18px;
      bottom: 18px;
      z-index: 20;
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: 12px;
    }

    .devtools-toggle {
      display: inline-flex;
      align-items: center;
      gap: 10px;
      border: 1px solid rgba(255, 255, 255, 0.12);
      border-radius: 999px;
      padding: 10px 14px;
      background: rgba(15, 23, 42, 0.96);
      color: #f8fafc;
      box-shadow: 0 14px 40px rgba(15, 23, 42, 0.32);
      cursor: pointer;
    }

    .devtools-dot {
      width: 9px;
      height: 9px;
      border-radius: 999px;
      background: #22c55e;
      box-shadow: 0 0 0 4px rgba(34, 197, 94, 0.18);
    }

    .devtools-icon {
      font-size: 12px;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
    }

    .devtools-panel {
      width: 260px;
      border-radius: 18px;
      padding: 16px;
      background: rgba(15, 23, 42, 0.97);
      color: #e2e8f0;
      border: 1px solid rgba(148, 163, 184, 0.25);
      box-shadow: 0 20px 45px rgba(15, 23, 42, 0.42);
      backdrop-filter: blur(16px);
    }

    .devtools-title {
      font-size: 14px;
      font-weight: 700;
    }

    .devtools-subtitle {
      margin-top: 2px;
      margin-bottom: 14px;
      color: #94a3b8;
      font-size: 12px;
    }

    .devtools-field {
      display: flex;
      flex-direction: column;
      gap: 6px;
      margin-bottom: 12px;
      font-size: 12px;
      color: #cbd5e1;
    }

    .devtools-field input {
      border: 1px solid rgba(148, 163, 184, 0.25);
      border-radius: 10px;
      background: rgba(30, 41, 59, 0.95);
      color: #f8fafc;
      padding: 10px 12px;
      font: inherit;
    }

    .devtools-field select {
      border: 1px solid rgba(148, 163, 184, 0.25);
      border-radius: 10px;
      background: rgba(30, 41, 59, 0.95);
      color: #f8fafc;
      padding: 10px 12px;
      font: inherit;
    }

    .devtools-actions {
      display: flex;
      justify-content: flex-end;
      gap: 10px;
      margin-top: 4px;
    }

    .devtools-actions button {
      border-radius: 10px;
      padding: 9px 12px;
      cursor: pointer;
      font-size: 12px;
      font-weight: 600;
    }

    .devtools-ghost {
      border: 1px solid rgba(148, 163, 184, 0.25);
      background: transparent;
      color: #cbd5e1;
    }

    .devtools-primary {
      border: none;
      background: linear-gradient(135deg, #38bdf8, #22c55e);
      color: #0f172a;
    }
  `]
})
export class AppComponent implements OnInit, OnDestroy {
  readonly availableVersions = AVAILABLE_VERSIONS;
  readonly currentVersion = typeof window === 'undefined'
    ? '35'
    : window.location.pathname.match(/-v(\d+)(?:\/|$)/)?.[1] ?? '35';
  private readonly allColumns: ColumnItem[] = [
    { field: 'id', headerName: 'Trade ID' },
    { field: 'orderId', headerName: 'Order ID' },
    { field: 'symbol', headerName: 'Symbol' },
    { field: 'side', headerName: 'Side' },
    { field: 'orderType', headerName: 'Type' },
    { field: 'quantity', headerName: 'Qty' },
    { field: 'filledQuantity', headerName: 'Filled' },
    { field: 'limitPrice', headerName: 'Limit' },
    { field: 'marketPrice', headerName: 'Market' },
    { field: 'avgPrice', headerName: 'Avg' },
    { field: 'notional', headerName: 'Notional' },
    { field: 'commission', headerName: 'Comm' },
    { field: 'status', headerName: 'Status' },
    { field: 'trader', headerName: 'Trader' },
    { field: 'account', headerName: 'Account' },
    { field: 'venue', headerName: 'Venue' },
    { field: 'currency', headerName: 'Curr' },
    { field: 'region', headerName: 'Region' },
    { field: 'sector', headerName: 'Sector' },
    { field: 'settlementDate', headerName: 'Settle' },
    { field: 'timestamp', headerName: 'Timestamp' },
    { field: 'priority', headerName: 'Priority' },
    { field: 'algo', headerName: 'Algo' },
    { field: 'executionVenue', headerName: 'Exec Venue' },
    { field: 'counterparty', headerName: 'Counterparty' },
    { field: 'bloombergId', headerName: 'BBG ID' },
    { field: 'ricCode', headerName: 'RIC' },
    { field: 'cusip', headerName: 'CUSIP' },
    { field: 'isin', headerName: 'ISIN' },
    { field: 'sedol', headerName: 'SEDOL' }
  ];

  columnDefs: ColDef[] = [];
  defaultColDef: ColDef = {
    sortable: true,
    resizable: true,
    suppressMovable: true
  };
  viewportDatasource!: IViewportDatasource & { refresh: () => void };
  serverConfig: MockServerConfig = { ...DEFAULT_CONFIG };
  draftConfig: MockServerConfig = { ...DEFAULT_CONFIG };
  gridConfig = { ...DEFAULT_GRID_CONFIG };
  draftGridConfig = { ...DEFAULT_GRID_CONFIG };
  devtoolsOpen = false;
  draftDirty = false;

  totalPnl = 0;
  tradeCount = 0;
  volume = 0;

  private gridApi!: GridApi;

  getRowId = (params: GetRowIdParams) => String(params.data?.__index);

  async ngOnInit() {
    this.updateGridColumns();
    try {
      const config = await getMockServerConfig();
      this.serverConfig = config;
      this.draftConfig = { ...config };
      this.gridConfig = { ...DEFAULT_GRID_CONFIG };
      this.draftGridConfig = { ...DEFAULT_GRID_CONFIG };
    } catch {
      this.serverConfig = { ...DEFAULT_CONFIG };
      this.draftConfig = { ...DEFAULT_CONFIG };
      this.gridConfig = { ...DEFAULT_GRID_CONFIG };
      this.draftGridConfig = { ...DEFAULT_GRID_CONFIG };
    }

    this.viewportDatasource = createViewportDatasource({
      onStats: (stats) => this.applyStats(stats),
      onRowCount: (rowCount) => {
        this.serverConfig = { ...this.serverConfig, totalRows: rowCount };
      },
      onConfig: (config) => {
        this.serverConfig = config;
        if (!this.devtoolsOpen || !this.draftDirty) {
          this.draftConfig = { ...config };
          this.draftGridConfig = { ...this.gridConfig };
          this.draftDirty = false;
        }
      },
      onRowsUpdated: (rows) => this.flashChangedCells(rows)
    });
  }

  async applyConfig() {
    const config = await updateMockServerConfig(this.draftConfig);
    this.serverConfig = config;
    this.draftConfig = { ...config };
    this.gridConfig = { ...this.draftGridConfig };
    this.draftDirty = false;
    this.viewportDatasource?.refresh();
  }

  resetDraftConfig() {
    this.draftConfig = { ...this.serverConfig };
    this.draftGridConfig = { ...this.gridConfig };
    this.draftDirty = false;
  }

  toggleDevtools() {
    this.devtoolsOpen = !this.devtoolsOpen;
    if (this.devtoolsOpen && !this.draftDirty) {
      this.draftConfig = { ...this.serverConfig };
      this.draftGridConfig = { ...this.gridConfig };
    }
  }

  private flashChangedCells(rows: UpdatedViewportRow[]) {
    if (!this.gridApi || rows.length === 0) {
      return;
    }

    requestAnimationFrame(() => {
      rows.forEach((row) => {
        const rowNode = this.gridApi.getRowNode(String(row.__index));
        if (!rowNode) {
          return;
        }

        const columns = (row.__changedFields ?? [])
          .map((field) => this.gridApi.getColumn(field))
          .filter((column): column is Column => !!column);

        if (columns.length === 0) {
          return;
        }

        this.gridApi.flashCells({
          rowNodes: [rowNode],
          columns
        });
      });
    });
  }

  private updateGridColumns() {
    const widthMap: Record<string, number> = {
      id: 110, orderId: 120, symbol: 70, side: 60, orderType: 80,
      quantity: 60, filledQuantity: 70, limitPrice: 80, marketPrice: 80,
      avgPrice: 80, notional: 110, commission: 70, status: 80,
      trader: 75, account: 75, venue: 70, currency: 60, region: 60,
      sector: 90, settlementDate: 90, timestamp: 160, priority: 70,
      algo: 80, executionVenue: 90, counterparty: 100, bloombergId: 90,
      ricCode: 80, cusip: 90, isin: 100, sedol: 80
    };

    this.columnDefs = this.allColumns.map((col) => {
      const colDef: ColDef = {
        field: col.field,
        headerName: col.headerName,
        width: widthMap[col.field] || 100
      };

      if (col.field === 'side') {
        colDef.cellStyle = (params: CellClassParams<Trade>) => params.value === 'BUY' ? { color: '#00ff88' } : { color: '#ff4757' };
      }

      if (col.field === 'status') {
        colDef.cellStyle = (params: CellClassParams<Trade>) => {
          const colors: Record<string, string> = { PENDING: '#ffa502', FILLED: '#00ff88', PARTIAL: '#00d4ff', CANCELLED: '#ff4757' };
          return { color: colors[String(params.value)] || '#eee' };
        };
      }

      if (['limitPrice', 'marketPrice', 'avgPrice', 'notional', 'commission'].includes(col.field)) {
        colDef.type = 'numericColumn';
        colDef.valueFormatter = (params) => params.value ? `$${Number(params.value).toFixed(2)}` : '';
        colDef.cellStyle = { textAlign: 'right' };
      }

      if (col.field === 'timestamp') {
        colDef.valueFormatter = (params) => params.value ? new Date(Number(params.value)).toISOString() : '';
      }

      if (col.field === 'id') {
        colDef.pinned = 'left';
      }

      return colDef;
    });

  }

  private applyStats(stats: MockServerStats) {
    this.totalPnl = stats.totalPnl;
    this.tradeCount = stats.tradeCount;
    this.volume = stats.volume;
  }

  ngOnDestroy() {
    this.viewportDatasource?.destroy?.();
  }

  switchVersion(version: string) {
    window.location.href = new URL(`../ag-grid-angular-v${version}/`, window.location.href).toString();
  }

  onGridReady(params: GridReadyEvent) {
    this.gridApi = params.api;
  }
}
